version: '3.6'

services:
  padslip:
    build:
      dockerfile: ./Dockerfile
      context: .
    container_name: padSlip_server
    environment:
      NODE_ENV: production
      REACT_APP_GRAPHQL_ENDPOINT: https://padslip.hasura.app/v1/graphql
      REACT_APP_HASURA_ADMIN_SECRET: zbhpeObcxIjCcva3tyUhIpkcwA2FV2UgkVTO2xdQ0uy6qHMQzcJ79AOOSIGTyMpR
    ports:
      - "5000:5000"
      - "3000:3000"
    restart: always
