version: '3.6'

services:
  postgres:
    image: postgres:12
    container_name: padSlip_postgres
    environment:
      POSTGRES_PASSWORD: padSlip
      POSTGRES_DB: padSlip_dashboard
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./postgresql:/var/lib/postgresql/data
  hasura:
    # image: hasura/graphql-engine:v2.33.3
    image: hasura/graphql-engine:v2.33.3.cli-migrations-v3
    container_name: padSlip_hasura
    depends_on:
      - "postgres"
    restart: always
    ports:
      - "8080:8080"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:padSlip@postgres:5432/padSlip_dashboard
      HASURA_GRAPHQL_ADMIN_SECRET: "padSlip"
    volumes:
      - ./hasura/migrations:/hasura-migrations
      - ./hasura/metadata:/hasura-metadata
  padslip:
    build:
      dockerfile: ./Dockerfile
      context: .
    container_name: padSlip_server
    depends_on:
      - hasura
      - postgres
    environment:
      NODE_ENV: production
      REACT_APP_GRAPHQL_ENDPOINT: https://padslip.hasura.app/v1/graphql
      REACT_APP_HASURA_ADMIN_SECRET: zbhpeObcxIjCcva3tyUhIpkcwA2FV2UgkVTO2xdQ0uy6qHMQzcJ79AOOSIGTyMpR
    ports:
      - "4000:4000"
      - "3000:3000"
    restart: always
